Linting / version check changes
- Use `python3 -mflake8` instead of `flake8`
- Allow python3 to be set by ${PYTHON3}
- Test for debootstrap ge 1.0.102 (if dpkg is installed; technically
  this can be run on a non-Debian system without dpkg)
- Only lint if LINT=true (I know I've gone back and forth on this a
  few times)

diff --git a/finnix-live-build b/finnix-live-build
--- a/finnix-live-build
+++ b/finnix-live-build
@@ -16,6 +16,7 @@ CACHE_FROZEN="${CACHE_FROZEN:-false}"
 SAVE_ISO="${SAVE_ISO:-false}"
 LINT="${LINT:-false}"
 BUILD_TAGS="${BUILD_TAGS:-}"
+PYTHON3="${PYTHON3:-python3}"
 
 lock() {
     _file=$1
@@ -55,10 +56,10 @@ render() {
 # Optional: git (git): Build IDs
 # Optional: file (file): Post-build file info
 
-host_commands="debootstrap python3 rsvg-convert"
+host_commands="debootstrap ${PYTHON3} rsvg-convert"
 missing_commands=""
 if [ "${LINT}" = "true" ]; then
-    host_commands="${host_commands} shellcheck flake8"
+    host_commands="${host_commands} shellcheck"
 fi
 for c in ${host_commands}; do
     command -v "${c}" >/dev/null || missing_commands="${missing_commands} ${c}"
@@ -66,6 +67,18 @@ done
 if [ -n "${missing_commands}" ]; then
     echo "ERROR: Missing required commands:${missing_commands}" >&2
     exit 1
+fi
+if command -v dpkg >/dev/null 2>/dev/null; then
+    if ! dpkg --compare-versions "$(debootstrap --version | cut -d' ' -f2)" ge 1.0.102; then
+        echo "ERROR: debootstrap 1.0.102 or later is required"
+        exit 1
+    fi
+fi
+if [ "${LINT}" = "true" ]; then
+    if ! "${PYTHON3}" -mflake8 /dev/null; then
+        echo "ERROR: flake8 is required for LINT=true"
+        exit 1
+    fi
 fi
 
 DATETIME="$(date -u +"%F %T")"
@@ -168,12 +181,10 @@ fi
 
 BUILD_TAGS="$(for i in ${BUILD_TAGS}; do echo "${i}"; done | sort | uniq | xargs)"
 
-if command -v shellcheck >/dev/null; then
+if [ "${LINT}" = "true" ]; then
     shellcheck "${BASE_DIR}/finnix-live-build"
     grep -l -E '^#!/(usr/)?bin/(env )?(ba)?sh' "${BASE_DIR}/tools"/* | xargs -r shellcheck
-fi
-if command -v flake8 >/dev/null; then
-    grep -l -E '^#!/(usr/)?bin/(env )?python3' "${BASE_DIR}/tools"/* | xargs -r flake8 --config=/dev/null --max-line-length=120
+    grep -l -E '^#!/(usr/)?bin/(env )?python3' "${BASE_DIR}/tools"/* | xargs -r "${PYTHON3}" -mflake8 --config=/dev/null --max-line-length=120
 fi
 
 mkdir -p "${LOCK_DIR}"
@@ -297,13 +308,11 @@ cat <<"EOM" >config/preseed/firmware-nonfree.cfg.chroot
 firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true
 EOM
 
-if command -v shellcheck >/dev/null; then
+if [ "${LINT}" = "true" ]; then
     grep -l -E '^#!/(usr/)?bin/(env )?(ba)?sh' "${LB_DIR}/config/hooks/normal"/*-finnix-*.hook.chroot | xargs -r shellcheck
     grep -l -E '^#!/(usr/)?bin/(env )?(ba)?sh' "${LB_DIR}/config/includes.chroot_after_packages/hook-files"/* | xargs -r shellcheck
-fi
-if command -v flake8 >/dev/null; then
-    grep -l -E '^#!/(usr/)?bin/(env )?python3' "${LB_DIR}/config/hooks/normal"/*-finnix-*.hook.chroot | xargs -r flake8 --config=/dev/null --max-line-length=120
-    grep -l -E '^#!/(usr/)?bin/(env )?python3' "${LB_DIR}/config/includes.chroot_after_packages/hook-files"/* | xargs -r flake8 --config=/dev/null --max-line-length=120
+    grep -l -E '^#!/(usr/)?bin/(env )?python3' "${LB_DIR}/config/hooks/normal"/*-finnix-*.hook.chroot | xargs -r "${PYTHON3}" -mflake8 --config=/dev/null --max-line-length=120
+    grep -l -E '^#!/(usr/)?bin/(env )?python3' "${LB_DIR}/config/includes.chroot_after_packages/hook-files"/* | xargs -r "${PYTHON3}" -mflake8 --config=/dev/null --max-line-length=120
 fi
 
 if [ "${LINT}" = "true" ]; then
