Requirements enhancements
- Pare down explicit required packages
- Document where requirements are used
- Check for required commands
- Fix assumptions about git being available
- Make file optional
- Re-introduce LINT=true checks during GitHub workflows

diff --git a/finnix-live-build b/finnix-live-build
--- a/finnix-live-build
+++ b/finnix-live-build
@@ -42,6 +42,31 @@ render() {
    "${BASE_DIR}/tools/jinja2-render"
 }
 
+# PACKAGES USED:
+# Required: debootstrap (debootstrap): live-build initial bootstrap
+# Required: debian-archive-keyring: live-build initial bootstrap
+# Required: python3 (python3): Templating
+# Required: python3-jinja2: Templating
+# Required: librsvg2-bin (rsvg-convert): splash.png
+# Required: fonts-liberation2: splash.png
+# Optional: shellcheck (shellcheck): Lint, required for LINT=true
+# Optional: flake8 (flake8): Lint, required for LINT=true
+# Optional: git (git): Build IDs
+# Optional: file (file): Post-build file info
+
+host_commands="debootstrap python3 rsvg-convert"
+missing_commands=""
+if [ "${LINT}" = "true" ]; then
+    host_commands="${host_commands} shellcheck flake8"
+fi
+for c in ${host_commands}; do
+    command -v "${c}" >/dev/null || missing_commands="${missing_commands} ${c}"
+done
+if [ -n "${missing_commands}" ]; then
+    echo "ERROR: Missing required commands:${missing_commands}" >&2
+    exit 1
+fi
+
 DATETIME="$(date -u +"%F %T")"
 DATE="$(date -u +"%F")"
 YEAR="$(date -u +"%Y")"
@@ -75,14 +100,6 @@ if [ "$(dnsdomainname)" = "snowman.lan" ]; then
 fi
 
 if [ "${LINT}" = "true" ]; then
-    if ! command -v shellcheck >/dev/null; then
-        echo "ERROR: LINT=true requires shellcheck" >&2
-        exit 1
-    fi
-    if ! command -v flake8 >/dev/null; then
-        echo "ERROR: LINT=true requires flake8" >&2
-        exit 1
-    fi
     LINT_DIR="$(mktemp -d)"
     DATA_DIR="${DATA_DIR:-${LINT_DIR}}"
 fi
@@ -98,7 +115,7 @@ LB_CACHE_DIR="${LB_CACHE_DIR:-${CACHE_DIR}/lb}"
 LIVE_BUILD="${LIVE_BUILD:-${BASE_DIR}/live-build}"
 
 GIT_DESC="$(git -C "${BASE_DIR}" describe --always --dirty 2>/dev/null || true)"
-git diff --quiet || BUILD_TAGS="${BUILD_TAGS} dirty"
+git diff --quiet 2>/dev/null || BUILD_TAGS="${BUILD_TAGS} dirty"
 LIVE_BUILD_GIT_DESC=""
 
 if [ "${LIVE_BUILD}" = "-" ]; then
@@ -270,7 +287,10 @@ fi
 
 lb build
 
-build_id="$(echo "${DATETIME}" | sed -e 's/ /_/g')_${GIT_DESC}"
+build_id="$(echo "${DATETIME}" | sed -e 's/ /_/g')"
+if [ -n "${GIT_DESC}" ]; then
+    build_id="${build_id}_${GIT_DESC}"
+fi
 build_size="$(stat -c "%s" "${LB_DIR}/${ISO_FILENAME}")"
 mkdir -p "${BUILD_INFO_DIR}/${build_id}"
 cp -a "${LB_DIR}"/*.contents "${BUILD_INFO_DIR}/${build_id}/"
@@ -283,7 +303,9 @@ if [ "${SAVE_ISO}" = "true" ]; then
 fi
 
 ls -lsa "${LB_DIR}/${ISO_FILENAME}"
-file "${LB_DIR}/${ISO_FILENAME}"
+if command -v file >/dev/null; then
+    file "${LB_DIR}/${ISO_FILENAME}"
+fi
 echo "Build: ${DATETIME} ${GIT_DESC} ${BUILD_TAGS}"
 echo
 
