Add pre-commit checks

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,57 +1,57 @@
 # SPDX-PackageSummary: finnix-live-build
 # SPDX-FileCopyrightText: Copyright (C) 2020-2024 Ryan Finnie
 # SPDX-License-Identifier: MPL-2.0
-
-name: release
-on:
+---
+name: "release"
+"on":
   workflow_dispatch:
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: "ubuntu-latest"
     permissions:
-      id-token: write
-      attestations: write
+      id-token: "write"
+      attestations: "write"
     steps:
-    - uses: actions/checkout@v4
-      with:
-        submodules: true
-    - name: Dependency packages
-      run: |
-        sudo apt update
-        sudo apt -y install $(tools/get-dependencies --only required)
-        for pkg in $(tools/get-dependencies --only optional); do
-          sudo apt -y install "${pkg}" || true
-        done
-    - name: Build image
-      run: |
-        # Prepare
-        env | grep ^GITHUB_ | sudo tee -a /etc/environment >/dev/null
-        sudo chown -R root:root .
+      - uses: "actions/checkout@v4"
+        with:
+          submodules: true
+      - name: "Dependency packages"
+        run: |
+          sudo apt update
+          sudo apt -y install $(tools/get-dependencies --only required)
+          for pkg in $(tools/get-dependencies --only optional); do
+            sudo apt -y install "${pkg}" || true
+          done
+      - name: "Build image"
+        run: |
+          # Prepare
+          env | grep ^GITHUB_ | sudo tee -a /etc/environment >/dev/null
+          sudo chown -R root:root .
 
-        # Main ISO image
-        sudo env BUILD_TAGS="release" ./finnix-live-build
+          # Main ISO image
+          sudo env BUILD_TAGS="release" ./finnix-live-build
 
-        # Source ISO
-        TEMP_DATA_DIR="$(sudo mktemp -d -p "$(pwd)/build")"
-        sudo env SOURCE_ISO=true DATA_DIR="${TEMP_DATA_DIR?}" ./finnix-live-build
-        sudo mv "${TEMP_DATA_DIR}/lb/finnix-source.iso" build/lb/
-        sudo rm -rf "${TEMP_DATA_DIR?}"
-        echo "Note: The build information listed above is not used; only the source ISO is saved."
-        echo "See the 'Build image' step for actual build information."
+          # Source ISO
+          TEMP_DATA_DIR="$(sudo mktemp -d -p "$(pwd)/build")"
+          sudo env SOURCE_ISO=true DATA_DIR="${TEMP_DATA_DIR?}" ./finnix-live-build
+          sudo mv "${TEMP_DATA_DIR}/lb/finnix-source.iso" build/lb/
+          sudo rm -rf "${TEMP_DATA_DIR?}"
+          echo "Note: The build information listed above is not used; only the source ISO is saved."
+          echo "See the 'Build image' step for actual build information."
 
-        # Cleanup
-        sudo chown -R "$(id -un):$(id -gn)" .
-    - name: Attest
-      uses: actions/attest-build-provenance@v1
-      with:
-        subject-path: '${{ github.workspace }}/build/lb/finnix-*.iso'
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: finnix-live-build.${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}
-        path: |
-          build/lb/finnix-*
-          build/lb/chroot.files
-          build/lb/chroot.packages.*
-        # Faster uploads as ISOs are already heavily compressed
-        compression-level: 0
+          # Cleanup
+          sudo chown -R "$(id -un):$(id -gn)" .
+      - name: "Attest"
+        uses: "actions/attest-build-provenance@v1"
+        with:
+          subject-path: "${{ github.workspace }}/build/lb/finnix-*.iso"
+      - name: "Upload artifacts"
+        uses: "actions/upload-artifact@v4"
+        with:
+          name: "finnix-live-build.${{ github.workflow }}.${{ github.job }}.${{ github.run_number }}.${{ github.run_id }}"
+          path: |
+            build/lb/finnix-*
+            build/lb/chroot.files
+            build/lb/chroot.packages.*
+          # Faster uploads as ISOs are already heavily compressed
+          compression-level: 0
